### ISSUE TITLE
Stadig sensorer med unknown status

### ISSUE THREAD

**Issue by edtwodth** [JonasPed/homeassistant-eloverblik#84]
Hej, har gennem hacs netop opdateret til seneste version, men får stadig unknown på følgende sensorer:

sensor.eloverblik_energy_statistic

og 

sensor.eloverblik_meter_reading

**Comment by WilliamHusum** [comment]
Det er meningen at i hvert fald sensor.eloverblik_energy_statistic skal vise unknown. 
`An entity with the id sensor.eloverblik_energy_statistic is created, this entity will always have an unknown value, since if a current value is set, the recorder will try to write it to the statistics.` [(link)](https://github.com/JonasPed/homeassistant-eloverblik#:~:text=An%20entity%20with%20the%20id%20sensor.eloverblik_energy_statistic%20is%20created%2C%20this%20entity%20will%20always%20have%20an%20unknown%20value%2C%20since%20if%20a%20current%20value%20is%20set%2C%20the%20recorder%20will%20try%20to%20write%20it%20to%20the%20statistics.)

sensor.eloverblik_meter_reading får jeg ikke unknown på.

**Comment by edtwodth** [comment]
Ok, fair nok. Men mystisk at jeg ingen data får på sensor.eloverblik_meter_reading når alt andet virker.

**Comment by JonasPed** [comment]
> Ok, fair nok. Men mystisk at jeg ingen data får på sensor.eloverblik_meter_reading når alt andet virker.

Står der noget i loggen?

**Comment by Noget6** [comment]
Min sensor.eloverblik_meter_reading er også unknown kan ikke se noget i min log.. er heller ikke super stærk i dette så måske overser jeg noget
