### ISSUE TITLE
Displaying total energy cost in energy dashboard

### ISSUE THREAD

**Issue by AlexLamond** [JonasPed/homeassistant-eloverblik#93]
I am using Eloverblik, and also have both Energidatasercice and NordPool installed. How can I configure Eloverblik to show the usage in the HA Energy dashboard, but also include the price per hour and thus day, month etc

**Comment by JonasPed** [comment]
I don't think that is possible. Eloverblik manually updates the long term statistics database by calling the appropriate HA functions. Reason for this is to display the data on the right date. This is not the normal way to do it as sensor data is normally "real time" and due to that you can not add costs as you would normally do.
